name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --release
          - command: fmt
            args: --all -- --check --color always
          - command: clippy
            args: --all-targets --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32
          ldproxy: true
      - name: Create env file
        run: |
          touch .env
          echo WLAN_SSID=${{ secrets.WLAN_SSID }} >> .env
          echo WLAN_PASSWORD=${{ secrets.WLAN_PASSWORD }} >> .env
          echo MQTT_URL=${{ secrets.MQTT_URL }} >> .env
          echo MQTT_USERNAME=${{ secrets.MQTT_USERNAME }} >> .env
          echo MQTT_PASSWORD=${{ secrets.MQTT_PASSWORD }} >> .env
          echo MQTT_CLIENT_ID=${{ secrets.MQTT_CLIENT_ID }} >> .env
          cat .env
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
